# Site settings
title: Vox Pupuli
description: >
  Vox Pupuli is a collective of Puppet module, tooling and documentation
  maintainers working together for the greater good.
baseurl: ""
url: "https://voxpupuli.org"
github_username:  voxpupuli
twitter_username: voxpupuliorg

# Build settings
markdown: kramdown
encoding: utf-8
timezone: Etc/UTC
permalink: /blog/:year/:month/:day/:title/
kramdown:
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge

collections:
  docs:
    output: true
  sponsors:
    output: false

navigation:
  - title: How to contribute
    url: /contributing/
  - title: Code of Conduct
    url: /coc/
  - title: Documentation
    url: /docs/
  - title: Leadership
    url: /elections/
  - title: Security
    url: /security/
  - title: Plugins
    url: /plugins/
  - title: Sponsoring
    url: /sponsoring/
  - title: Blog
    url: /blog/

exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md", "CNAME", "vendor"]

plugins:
  - jekyll-last-modified-at
  - jekyll-redirect-from
